config/routes.rb
Rails.application.routes.draw do
  get '/second' => 'home#second'
  get '/third' => 'home#third'
  get '/first' => 'home#first'
  get '/new' => 'home#new'
  get '/hit' => 'home#hit'
  get '/stay' => 'home#start_dealer'
  get '/reset' => 'home#reset'
  post 'home/new' => 'home#create'
  root 'home#reset'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
    after_initialize :init

    def init
      self.username ||= "John Doe"
      self.wins  ||= 0
      self.losses ||=0
      self.current_tokens ||=100          
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/game_controller.rb
class GameController < HomeController

    def initialize
      @count = 0
      @token = 100
    end

  end

app/controllers/home_controller.rb
class HomeController < ApplicationController 

  def first
    session[:playerCount] ||=0
    session[:dealerCount] ||=0
    session[:initial] ||= 0 
    @@check = session[:initial]
    if @@check == 0
      deck_id
      initial_table
    end
    if @@check == 2
      if session[:dealerCount] > 21
        @@message_value = "YOU DOUBLED UP!"
      elsif session[:playerCount] > session[:dealerCount]
          @@message_value = "YOU DOUBLED UP!"
      elsif session[:dealerCount] > session[:playerCount]
        @@message_value = "YOU LOST!"
      else
        @@message_value = "TAKE YOUR MONEY BACK!"
      end
    end
    @message = @@message_value
    @player_count = session[:playerCount]
    @dealer_count = session[:dealerCount]
    @cards_dealer = @@card_dealer_json
    @cards_player = @@card_player_json
  end

  def second
  end

  def third
    @users = UserDetail.all
  end

  def new 
    @user = UserDetail.new
  end

  def create
    @user = UserDetail.create(params.require(:user_detail).permit(:name, :username))
    redirect_to "/first"
  end

  def reset
    reset_session
    redirect_to "/first"
  end

  def start_dealer
    while session[:dealerCount] < 17
      get_dealer_card
      get_dealer_count
    end
    session[:initial]+=1
    redirect_to "/first"
  end

  
  def hit
    if session[:playerCount] > 21
      @@message_value = "BUSTED"
    else
      get_card
      get_player_count
    end
    redirect_to "/first"
  end

  private
  def deck_id
    @res = RestClient.get 'https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1'
    @@data = JSON.parse @res
  end

  private 
  def initial_table
    @@message_value = ""
    card_dealer = RestClient.get "https://deckofcardsapi.com/api/deck/#{@@data["deck_id"]}/draw/?count=1"
    card_player = RestClient.get "https://deckofcardsapi.com/api/deck/#{@@data["deck_id"]}/draw/?count=2"
    dealer_json = JSON.parse card_dealer
    @@card_dealer_json = dealer_json["cards"]
    player_json = JSON.parse card_player
    @@card_player_json = player_json["cards"]
    get_player_count
    get_dealer_count
    session[:initial]+=1
    puts @@card_player_json
  end

  private
  def get_card
    new_card = RestClient.get "https://deckofcardsapi.com/api/deck/#{@@data["deck_id"]}/draw/?count=1"
    new_card_json = JSON.parse new_card
    new_card = new_card_json["cards"][0]
    @@card_player_json.push(new_card)
  end

  private
  def get_dealer_card
    new_card = RestClient.get "https://deckofcardsapi.com/api/deck/#{@@data["deck_id"]}/draw/?count=1"
    new_card_json = JSON.parse new_card
    new_card = new_card_json["cards"][0]
    @@card_dealer_json.push(new_card)
  end

  private 
  def get_dealer_count
    session[:dealerCount] = 0
    @@card_dealer_json.each do |item|
      if item["value"] == "JACK"
        session[:dealerCount] += 10
      elsif item["value"] == "KING"
        session[:dealerCount] += 10
      elsif item["value"] == "QUEEN"
        session[:dealerCount] += 10
      elsif item["value"] == "ACE"
        session[:dealerCount] += 1
      else
      session[:dealerCount]+= item["value"].to_i
      end
    end
  end

  private 
  def get_player_count
    session[:playerCount] = 0
    @@card_player_json.each do |item|
      if item["value"] == "JACK"
        session[:playerCount] += 10
      elsif item["value"] == "KING"
        session[:playerCount] += 10
      elsif item["value"] == "QUEEN"
        session[:playerCount] += 10
      elsif item["value"] == "ACE"
        session[:playerCount] += 1
      else
      session[:playerCount]+= item["value"].to_i
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Home Page', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Rules', second_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to 'User Information', third_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Create', new_path, class:"nav-link active"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/first.html.erb
<%= stylesheet_link_tag "first"%>
<div class = "Cards_Dealer row">
<div class = "col">
<% @cards_dealer.each do |c| %>
    <img src = <%=c["image"]%> class="rounded float-left" width="140" height = "200" alt = "#{c["value"]} of #{c["suit"]}"/> 
<% end %>
<h1 class = "count">COUNT : <%=@dealer_count%></h1>
</div>
</div>
<div class = "row">
    <div class = "col">
        <h1 class = "message"><%=@message%></h1>
    </div>
</div>
<div class = "Cards_Player row"> 
<div class = "col">
<% @cards_player.each do |c| %>
    <img src = <%=c["image"]%> class="rounded float-left" width="140" height = "200" alt = "#{c["value"]} of #{c["suit"]}"/> 
<% end %>
<h1 class = "count">COUNT : <%=@player_count%></h1>
</div>
</div>  
<div class = "row hit">
    <div class = "col"></div>
    <div class = "col">
        <%= link_to "HIT", "hit", class: "btn btn-warning btn-lg" %>
    </div>
    <div class = "col">
        <%= link_to "RESET", "reset", class: "btn btn-warning btn-lg" %>
    </div>
    <div class = "col">
    <%= link_to "STAY", "stay", class: "btn btn-warning btn-lg" %>
    </div>
</div>
<p>Images Taken: https://deckofcardsapi.com/ </p>

app/views/home/new.html.erb
<h1>Enter Your Information</h1>
<hr/>
<%= form_for @user, url: home_new_path(@user) do |f| %>
    Name: <%= f.text_field :name%> <br/>
    Username: <%= f.text_field :username%> <br/>
    <%= f.submit "Submit Details"%>
<% end %>

app/views/home/second.html.erb
<%= stylesheet_link_tag "second"%>
<div class="container">
    <div class = "row">
        <div class = "col">
        </div>
        <div class = "col-6">
            <h1>Rules!</h1>
            <hr/>
            <br/>
            <h4>The Pack </h4>
            <p>The standard 52-card pack is used, but in most casinos several decks of cards are 
            shuffled together. The six-deck game (312 cards) is the most popular. In addition, the dealer 
            uses a blank plastic card, which is never dealt, but is placed toward the bottom of the pack to 
            indicate when it will be time for the cards to be reshuffled. When four or more decks are used, 
            they are dealt from a shoe (a box that allows the dealer to remove cards one at a time, face down, 
            without actually holding one or more packs).</p>
            <hr/>
            <br/>
            <h4>OBJECT OF THE GAME</h4>
            <p>Each participant attempts to beat the dealer by getting a count as close to 21 as possible, without 
            going over 21.</p>
            <hr/>
            <br/>
            <h4>CARD VALUES/SCORING</h4>
            <p>It is up to each individual player if an ace is worth 1 or 11. Face cards are 10 and any other card is its pip value.</p>
            <hr/>
            <br/>
            <h4>BETTING</h4>
            <p>Before the deal begins, each player places a bet, in chips, in front of them in the designated area. Minimum and maximum limits are established on the betting, and the general limits are from $2 to $500.</p>
            <hr/>
            <br/>
            <h4>THE SHUFFLE AND CUT</h4>
            <p>The dealer thoroughly shuffles portions of the pack until all the cards have been mixed and combined. The dealer designates one of the players to cut, and the plastic insert card is placed so that the last 60 to 75 cards or so will not be used. (Not dealing to the bottom of all the cards makes it more difficult for professional card counters to operate effectively.)</p>
            <hr/>
            <br/>
            <h4>THE DEAL</h4>
            <p>When all the players have placed their bets, the dealer gives one card face up to each player in rotation clockwise, and then one card face up to themselves. Another round of cards is then dealt face up to each player, but the dealer takes the second card face down. Thus, each player except the dealer receives two cards face up, and the dealer receives one card face up and one card face down. (In some games, played with only one deck, the players' cards are dealt face down and they get to hold them. Today, however, virtually all Blackjack games feature the players' cards dealt face up on the condition that no player may touch any cards.)</p>
            <hr/>
            <br/>
            <h4>NATURALS</h4>
            <p>If a players first two cards are an ace and a ten-card (a picture card or 10), giving a count of 21 in two cards, this is a natural or "blackjack." If any player has a natural and the dealer does not, the dealer immediately pays that player one and a half times the amount of their bet. If the dealer has a natural, they immediately collect the bets of all players who do not have naturals, (but no additional amount). If the dealer and another player both have naturals, the bet of that player is a stand-off (a tie), and the player takes back his chips.</p>
            <br/>
            <p>If the dealers face-up card is a ten-card or an ace, they look at their face-down card to see if the two cards make a natural. If the face-up card is not a ten-card or an ace, they do not look at the face-down card until it is the dealers turn to play.</p>
            <hr/>
            <br/>
            <h4>THE PLAY</h4>
            <p>The player to the left goes first and must decide whether to "stand" (not ask for another card) or "hit" (ask for another card in an attempt to get closer to a count of 21, or even hit 21 exactly). Thus, a player may stand on the two cards originally dealt to them, or they may ask the dealer for additional cards, one at a time, until deciding to stand on the total (if it is 21 or under), or goes "bust" (if it is over 21). In the latter case, the player loses and the dealer collects the bet wagered. The dealer then turns to the next player to their left and serves them in the same manner.</p>
            <br/>
            <p>The combination of an ace with a card other than a ten-card is known as a "soft hand," because the player can count the ace as a 1 or 11, and either draw cards or not. For example with a "soft 17" (an ace and a 6), the total is 7 or 17. While a count of 17 is a good hand, the player may wish to draw for a higher total. If the draw creates a bust hand by counting the ace as an 11, the player simply counts the ace as a 1 and continues playing by standing or "hitting" (asking the dealer for additional cards, one at a time).</p>
            <hr/>
            <br/>
            <h4>THE DEALERS PLAY
            </h4>
            <p>When the dealer has served every player, the dealers face-down card is turned up. If the total is 17 or more, it must stand. If the total is 16 or under, they must take a card. The dealer must continue to take cards until the total is 17 or more, at which point the dealer must stand. If the dealer has an ace, and counting it as 11 would bring the total to 17 or more (but not over 21), the dealer must count the ace as 11 and stand. The dealers decisions, then, are automatic on all plays, whereas the player always has the option of taking one or more cards.</p>
            <hr/>
            <br/>
            <h4>BASIC STRATEGY</h4>
            <p>Winning tactics in Blackjack require that the player play each hand in the optimum way, and such strategy always takes into account what the dealer's upcard is. When the dealer's upcard is a good one, a 7, 8, 9, 10-card, or ace for example, the player should not stop drawing until a total of 17 or more is reached. When the dealer's upcard is a poor one, 4, 5, or 6, the player should stop drawing as soon as he gets a total of 12 or higher. The strategy here is never to take a card if there is any chance of going bust. The desire with this poor holding is to let the dealer hit and hopefully go over 21. Finally, when the dealer's up card is a fair one, 2 or 3, the player should stop with a total of 13 or higher.</p>
            <br/>
            <p>With a soft hand, the general strategy is to keep hitting until a total of at least 18 is reached. Thus, with an ace and a six (7 or 17), the player would not stop at 17, but would hit.

            The basic strategy for doubling down is as follows: With a total of 11, the player should always double down. With a total of 10, he should double down unless the dealer shows a ten-card or an ace. With a total of 9, the player should double down only if the dealers card is fair or poor (2 through 6).</p> 
            <br/>
            <p>For splitting, the player should always split a pair of aces or 8s; identical ten-cards should not be split, and neither should a pair of 5s, since two 5s are a total of 10, which can be used more effectively in doubling down. A pair of 4s should not be split either, as a total of 8 is a good number to draw to. Generally, 2s, 3s, or 7s can be split unless the dealer has an 8, 9, ten-card, or ace. Finally, 6s should not be split unless the dealers card is poor (2 through 6).</p>
            <hr/>
            <p>Rules Taken From: https://bicyclecards.com/how-to-play/blackjack/ </p>    
        </div>
        <div class = "col">
        </div>
    </div>
</div>

app/views/home/third.html.erb
<h1>Current Users!</h1>
<div class = "container">
    <div class = "row">
    <% @users.each do |user| %>
        <div class = "col set"> 
            <h3>Username: <%=user[:username]%><h3>
            <h3>Hands Won: <%=user[:wins]%></h3>
            <h3>Hands Lost: <%=user[:losses]%></h3>
            <h3>Current Tokens: <%=user[:current_tokens]%></h3>
        </div>
    <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Himanshu App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header'%>
    <br/>
    <div class="container">
      <div class = "row"> 
        <div class = "col">
        </div>
        <div class = "col">
          <h1 class = "head">BLACKJACK</h1>
        </div>
        <div class = "col">
        </div>
      </div>
      <br/>
      <%= yield %>
      </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>